"""Pure, conservative plausibility helpers for settled Fire Feast matches."""

import math


MAX_PLAUSIBLE_TAPS_PER_SECOND = 20
TAP_BURST_ALLOWANCE = 30
MIN_ACCEPTED_INPUT_INTERVAL_MS = 1000 / MAX_PLAUSIBLE_TAPS_PER_SECOND

# Floating-point progress is accumulated on the client. This epsilon only
# covers representation drift and scales very slightly with genuine activity.
PROGRESS_EPSILON_BASE = 0.001
PROGRESS_EPSILON_PER_TAP = 0.000001

# Score is accumulated as floating point and displayed with floor(). A 3%
# activity-scaled ceiling tolerates timer/frame ordering without granting any
# score when the underlying plausible score is zero.
SCORE_RELATIVE_TOLERANCE = 1.03
MAX_SAFE_MATCH_SCORE = 10_000_000

FRESH_STOMACH_DURATION_SECONDS = 5
FRESH_STOMACH_SCORE_MULTIPLIER = 1.1
HEAT_SHIELD_DURATION_SECONDS = 2
NATURAL_COOLING_PER_SECOND = 9
HOT_THRESHOLD = 80
HOT_TAP_EFFECTIVENESS = 0.9
MIN_TAP_EFFECTIVENESS = 0.75
ANTACID_MAX_HEAT_RELIEF = 40
PERFECT_COOLDOWN_BONUS = 5
PERFECT_COOLDOWN_HEAT_REQUIREMENT = 85

# The client displays an integer target generated by the backend, so only a
# one-point diagnostic difference is needed for end-of-timer ordering.
OPPONENT_SCORE_DIAGNOSTIC_TOLERANCE = 1


BASE_PERK_MODIFIERS = {
    "tap_power": 1.0,
    "combo_window_ms": 700,
    "score_multiplier": 1.0,
    "heat_generation_multiplier": 1.0,
}
GEAR_PERK_MODIFIERS = {
    "tap_boost": {
        "tap_power": 2.0,
        "combo_window_ms": 700,
        "score_multiplier": 1.0,
        "heat_generation_multiplier": 1.1,
    },
    "combo_boost": {
        "tap_power": 1.0,
        "combo_window_ms": 875,
        "score_multiplier": 1.0,
        "heat_generation_multiplier": 1.0,
    },
    "score_multiplier": {
        "tap_power": 1.0,
        "combo_window_ms": 700,
        "score_multiplier": 1.5,
        "heat_generation_multiplier": 1.15,
    },
}

FOOD_HEAT_BY_CONTEST = {
    "nathans-hotdogs": 5,
    "wing-bowl": 7,
    "pizza-hut-stuffed": 6,
    "katz-pastrami": 7,
    "ben-jerry-icecream": 5,
    "in-n-out-burgers": 6,
}


def trusted_heat_per_tap(contest: dict) -> int:
    base = FOOD_HEAT_BY_CONTEST.get(str(contest.get("id")), 5)
    difficulty = {
        "easy": 0.8,
        "hard": 1.2,
        "legendary": 1.0,
    }.get(str(contest.get("difficulty", "")).lower(), 1.0)
    # Mirrors JavaScript Math.round for the positive gameplay values used here.
    return math.floor(base * difficulty + 0.5)


def authoritative_perk_config(equipped_gear) -> tuple[str | None, dict]:
    """Resolve exactly one persisted gear identifier using trusted rules."""
    if equipped_gear not in GEAR_PERK_MODIFIERS:
        return None, dict(BASE_PERK_MODIFIERS)
    return equipped_gear, dict(GEAR_PERK_MODIFIERS[equipped_gear])


def build_opponent_config(opponent: dict, contest: dict, seed: int) -> dict:
    """Create the trusted deterministic opponent target shared with the client."""
    duration = max(1, int(contest.get("duration_sec", 1)))
    tap_speed = max(0.1, float(opponent.get("tap_speed", 1)))
    accuracy = min(1.0, max(0.1, float(opponent.get("accuracy", 0.75))))
    combo_skill = min(1.0, max(0.0, float(opponent.get("combo_skill", 0))))
    difficulty_factor = {
        "easy": 0.9,
        "medium": 1.0,
        "hard": 1.05,
        "legendary": 1.1,
    }.get(str(contest.get("difficulty", "")).lower(), 1.0)
    variation = 0.94 + (seed % 1201) / 10_000
    final_score = max(
        1,
        round(
            duration
            * tap_speed
            * accuracy
            * (1 + combo_skill * 0.25)
            * difficulty_factor
            * variation
        ),
    )
    return {
        "seed": seed,
        "final_score": final_score,
        "pace_per_sec": final_score / duration,
        "duration_sec": duration,
        "opponent": {
            "id": opponent.get("id"),
            "name": opponent.get("name"),
            "title": opponent.get("title"),
            "emoji": opponent.get("emoji"),
            "difficulty": opponent.get("difficulty"),
            "tap_speed": tap_speed,
            "accuracy": accuracy,
            "combo_skill": combo_skill,
            "aggression": min(1.0, max(0.0, float(opponent.get("aggression", 0.5)))),
        },
    }


def authoritative_opponent_score(active: dict) -> int | None:
    config = active.get("opponent_config")
    if not isinstance(config, dict):
        return None
    score = config.get("final_score")
    if not isinstance(score, int) or isinstance(score, bool) or score < 0:
        return None
    return score


def progress_epsilon(accepted_taps: int) -> float:
    return PROGRESS_EPSILON_BASE + accepted_taps * PROGRESS_EPSILON_PER_TAP


def maximum_taps_for_duration(duration_sec: float) -> int:
    return math.ceil(duration_sec * MAX_PLAUSIBLE_TAPS_PER_SECOND + TAP_BURST_ALLOWANCE)


def maximum_antacid_uses(duration_sec: int) -> int:
    # A successful use starts a two-second shield. The gameplay control cannot
    # consume another antacid while that shield is active.
    return math.floor(duration_sec / HEAT_SHIELD_DURATION_SECONDS) + 1


def combo_gain_for_maximum_combo(maximum_combo: int) -> float:
    if maximum_combo >= 20:
        return 3.0
    if maximum_combo >= 10:
        return 2.0
    if maximum_combo >= 5:
        return 1.5
    return 1.0


def maximum_combo_for_timing(
    accepted_taps: int,
    duration_sec: int,
    combo_window_ms: int,
) -> int:
    if accepted_taps <= 1 or combo_window_ms < MIN_ACCEPTED_INPUT_INTERVAL_MS:
        return 0
    rate_bound = math.floor(duration_sec * 1000 / MIN_ACCEPTED_INPUT_INTERVAL_MS)
    # The first accepted action starts at combo zero. A longer combo window
    # helps maintain the chain but cannot manufacture actions.
    return max(0, min(accepted_taps - 1, rate_bound - 1))


def maximum_heat_aware_progress(
    accepted_taps: int,
    duration_sec: int,
    antacids_used: int,
    tap_power: float,
    heat_per_tap: float,
    heat_generation_multiplier: float,
) -> float:
    if accepted_taps <= 0:
        return 0.0
    heat_gain = max(0.0, heat_per_tap * heat_generation_multiplier)
    if heat_gain == 0:
        return accepted_taps * tap_power

    # This is intentionally player-favorable: cooling is allowed for the full
    # match, every antacid receives the larger pre-overheat reduction, and each
    # shield may cover a full maximum-rate two-second burst. Any remaining taps
    # must at least pay the 10% hot-state effectiveness reduction.
    cooling_budget = duration_sec * NATURAL_COOLING_PER_SECOND
    relief_budget = antacids_used * ANTACID_MAX_HEAT_RELIEF
    shielded_taps = antacids_used * math.ceil(
        HEAT_SHIELD_DURATION_SECONDS * MAX_PLAUSIBLE_TAPS_PER_SECOND
    )
    cool_taps = math.floor((HOT_THRESHOLD + cooling_budget + relief_budget) / heat_gain)
    full_effect_taps = min(accepted_taps, cool_taps + shielded_taps)
    hot_taps = accepted_taps - full_effect_taps
    return tap_power * (full_effect_taps + hot_taps * HOT_TAP_EFFECTIVENESS)


def maximum_score_for_telemetry(
    *,
    accepted_taps: int,
    completed_progress: float,
    maximum_combo: int,
    duration_sec: int,
    antacids_used: int,
    tap_power: float,
    score_multiplier: float,
    heat_per_tap: float,
    heat_generation_multiplier: float,
) -> int:
    if accepted_taps <= 0 or completed_progress <= 0:
        return 0
    combo_gain = combo_gain_for_maximum_combo(maximum_combo)
    # Critical heat (1.5x) is the strongest legitimate heat-tier multiplier.
    base_factor = combo_gain * 1.5 * score_multiplier
    fresh_actions = min(
        accepted_taps,
        math.ceil(
            min(duration_sec, antacids_used * FRESH_STOMACH_DURATION_SECONDS)
            * MAX_PLAUSIBLE_TAPS_PER_SECOND
        ),
    )
    fresh_progress = min(completed_progress, fresh_actions * tap_power)
    score_before_cooldowns = base_factor * (
        completed_progress
        + fresh_progress * (FRESH_STOMACH_SCORE_MULTIPLIER - 1)
    )
    total_heat = accepted_taps * heat_per_tap * heat_generation_multiplier
    maximum_cooldown_cycles = min(
        math.floor(total_heat / PERFECT_COOLDOWN_HEAT_REQUIREMENT),
        math.floor(duration_sec / 3),
    )
    perfect_cooldown_score = maximum_cooldown_cycles * PERFECT_COOLDOWN_BONUS
    plausible = score_before_cooldowns + perfect_cooldown_score
    return min(MAX_SAFE_MATCH_SCORE, math.ceil(plausible * SCORE_RELATIVE_TOLERANCE))


def minimum_progress_for_taps(accepted_taps: int, tap_power: float) -> float:
    return accepted_taps * tap_power * MIN_TAP_EFFECTIVENESS
