const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const frontendRoot = path.resolve(__dirname, "..");
const repositoryRoot = path.resolve(frontendRoot, "..");
const legalDirectory = path.join(repositoryRoot, "docs", "legal");
const generatedPath = path.join(frontendRoot, "src", "legal", "generatedLegalDocuments.ts");
const legalScreenPath = path.join(frontendRoot, "app", "legal", "[document].tsx");
const settingsPath = path.join(frontendRoot, "app", "settings.tsx");
const profilePath = path.join(frontendRoot, "app", "(tabs)", "profile.tsx");

const documents = [
  ["privacy", "privacy-policy.md"],
  ["terms", "terms-of-service.md"],
  ["disclaimer", "gameplay-disclaimer.md"],
];

function read(file) {
  return fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");
}

function expectedGeneratedSource() {
  return [
    "// Generated from docs/legal by scripts/sync-legal-docs.js.",
    "// Do not edit this file directly; update the canonical Markdown and rerun the sync script.",
    "",
    'export type LegalDocumentKey = "privacy" | "terms" | "disclaimer";',
    "",
    "export const LEGAL_DOCUMENTS: Readonly<Record<LegalDocumentKey, string>> = {",
    ...documents.map(([key, filename]) => `  ${key}: ${JSON.stringify(read(path.join(legalDirectory, filename)))},`),
    "};",
    "",
  ].join("\n");
}

test("final legal documents contain no placeholders and use the approved operator contacts", () => {
  const legalSources = documents.map(([, filename]) => read(path.join(legalDirectory, filename)));
  const userFacingSources = [...legalSources, read(generatedPath), read(settingsPath)].join("\n");

  assert.doesNotMatch(userFacingSources, /\b(?:TODO|FIXME)\b/i);
  assert.doesNotMatch(userFacingSources, /support@firefeast\.app|example@|example\.com|TODO Support Email|TODO Website/i);
  for (const markdown of legalSources) {
    assert.match(markdown, /\*\*Effective Date:\*\* 2026-08-04/);
    assert.match(markdown, /\*\*Last Updated:\*\* 2026-08-(?:04|07)/);
    assert.match(markdown, /support@firefeastgame\.com/);
    assert.match(markdown, /https:\/\/firefeastgame\.com/);
  }
});

test("generated legal documents exactly match the canonical Markdown sources", () => {
  assert.equal(read(generatedPath), expectedGeneratedSource());
});

test("all legal documents are registered with the shared render screen", () => {
  const screen = read(legalScreenPath);
  assert.match(screen, /privacy:\s*\{\s*title:\s*"PRIVACY POLICY",\s*markdown:\s*LEGAL_DOCUMENTS\.privacy/);
  assert.match(screen, /terms:\s*\{\s*title:\s*"TERMS OF SERVICE",\s*markdown:\s*LEGAL_DOCUMENTS\.terms/);
  assert.match(screen, /disclaimer:\s*\{\s*title:\s*"GAMEPLAY & HEALTH DISCLAIMER",\s*markdown:\s*LEGAL_DOCUMENTS\.disclaimer/);
  assert.match(screen, /<MarkdownDocument markdown=\{content\.markdown\}/);
  assert.match(screen, /<ScrollView/);
});

test("settings exposes legal documents and approved support channels", () => {
  const settings = read(settingsPath);
  assert.match(settings, /SUPPORT_EMAIL = "support@firefeastgame\.com"/);
  assert.match(settings, /PUBLIC_WEBSITE_URL = "https:\/\/firefeastgame\.com"/);
  assert.match(settings, /ACCOUNT_DELETION_URL = "https:\/\/firefeastgame\.com\/delete-account"/);
  for (const key of ["privacy", "terms", "disclaimer"]) {
    assert.match(settings, new RegExp(`document: "${key}"`));
  }
  assert.match(settings, /title="CONTACT SUPPORT"/);
  assert.match(settings, /title="FIRE FEAST WEBSITE"/);
  assert.match(settings, /title="REPORT A BUG"/);
  assert.match(settings, /title="REQUEST ACCOUNT DELETION"/);
});

test("account deletion remains reachable from Profile", () => {
  const profile = read(profilePath);
  assert.match(profile, /ACCOUNT &amp; DATA/);
  assert.match(profile, /title="DELETE ACCOUNT"/);
  assert.match(profile, /api\.deleteAccount\(\)/);
  assert.match(profile, /Delete Account Permanently/);
  assert.match(profile, /This cannot be undone/);
});
